'use client';

import Link from 'next/link';
import { allServices, ServicePage } from '../data';
import { QuoteForm } from './QuoteForm';

export function SectionHeading({ eyebrow, title, children, light = false }: { eyebrow?: string; title: string; children?: React.ReactNode; light?: boolean }) { return <div style={{maxWidth:850}}><p className="mono label" style={{color:light?'var(--red-bright)':'var(--red)'}}>{eyebrow}</p><h2 className="display" style={{fontSize:'clamp(3rem,8vw,7.5rem)',margin:0}}>{title}</h2>{children && <div style={{fontSize:'1.1rem',maxWidth:650,marginTop:24,color:light?'var(--muted)':'var(--muted-dark)'}}>{children}</div>}</div>; }

export function ServiceCard({ service }: { service: ServicePage }) { return <article className="service-card"><p className="mono">{service.category}</p><h3 className="display">{service.title}</h3><p>{service.intro}</p><Link href={`/${service.slug}/`} className="arrow-link">Explore service <span aria-hidden="true">↗</span></Link><style jsx>{`.service-card{border-top:1px solid var(--bone-rule);padding:24px 0;display:flex;flex-direction:column;min-height:250px}.service-card h3{font-size:clamp(2rem,4vw,3.5rem);margin:0 0 12px}.service-card p:not(.mono){color:var(--muted-dark);max-width:42ch}.arrow-link{font-weight:700;margin-top:auto;color:var(--red)}.arrow-link span{font-size:1.4rem;margin-left:8px}`}</style></article>; }

export function QuoteSection() { return <section className="dark section"><div className="wrap quote-layout"><div><SectionHeading light eyebrow="Start with the scope" title="Tell us what comes next."><p>Share project basics and a Matrix Demolition representative can review the request. No address or hours claim needed: call when you need immediate assistance.</p></SectionHeading><a className="btn btn-outline" href="tel:8175978490">Call 817-597-8490</a></div><QuoteForm /><style jsx>{`.quote-layout{display:grid;grid-template-columns:.8fr 1.2fr;gap:clamp(2rem,7vw,7rem);align-items:start}.quote-layout :global(.btn){margin-top:32px}@media(max-width:850px){.quote-layout{grid-template-columns:1fr}}`}</style></div></section>; }

export function ServiceDetail({ service }: { service: ServicePage }) { return <><section className="dark section"><div className="wrap"><p className="mono" style={{color:'var(--red-bright)'}}>Services / {service.category}</p><h1 className="display" style={{fontSize:'clamp(3.5rem,9vw,9rem)',maxWidth:1100,margin:'18px 0'}}>{service.title}</h1><p style={{fontSize:'clamp(1.1rem,2vw,1.4rem)',maxWidth:700,color:'var(--muted)'}}>{service.intro}</p><div style={{display:'flex',gap:12,flexWrap:'wrap',marginTop:32}}><Link className="btn btn-primary" href="/contact-us/#quote">Get a free quote</Link><a className="btn btn-outline" href="tel:8175978490">817-597-8490</a></div></div></section><section className="section"><div className="wrap"><SectionHeading eyebrow="Scope" title="What's included" /><div className="item-grid">{service.items.map((item,index)=><div key={item} className="item"><span className="mono">0{index+1}</span><h3>{item}</h3></div>)}</div>{service.process && <div style={{marginTop:'clamp(4rem,8vw,8rem)'}}><SectionHeading eyebrow="Process" title="A clear path forward" /><div className="process-grid">{service.process.map((step,index)=><div key={step} className="process"><span className="display">0{index+1}</span><h3>{step}</h3></div>)}</div></div>}{service.note && <div className="note"><p className="mono">Why Matrix</p><p>{service.note}</p></div>}</div><style jsx>{`.item-grid{display:grid;grid-template-columns:repeat(2,1fr);gap:0 48px;margin-top:48px}.item{border-top:1px solid var(--bone-rule);padding:22px 0;display:grid;grid-template-columns:60px 1fr;gap:16px;align-items:start}.item h3{font-size:1.3rem;margin:0}.item .mono{color:var(--red)}.process-grid{display:grid;grid-template-columns:repeat(4,1fr);margin-top:48px}.process{padding:20px;border-top:1px solid var(--bone-rule);border-left:1px solid var(--bone-rule)}.process .display{font-size:4rem;color:var(--red)}.process h3{font-size:1.1rem;margin:16px 0 0}.note{margin-top:56px;background:var(--ink);color:var(--bone);padding:32px;max-width:700px}.note .mono{color:var(--red-bright)}@media(max-width:700px){.item-grid{grid-template-columns:1fr}.process-grid{grid-template-columns:1fr 1fr}}`}</style></section><RelatedServices current={service.slug} /><QuoteSection /></>; }

export function RelatedServices({ current }: { current: string }) { return <section className="red" style={{paddingBlock:'clamp(3rem,7vw,6rem)'}}><div className="wrap" style={{display:'flex',justifyContent:'space-between',alignItems:'end',gap:24,flexWrap:'wrap'}}><div><p className="mono">Keep exploring</p><h2 className="display" style={{fontSize:'clamp(3rem,6vw,6rem)',margin:0}}>More ways to move forward.</h2></div><Link className="btn btn-dark" href="/our-services/">View all services</Link></div><div className="wrap related-grid">{allServices.filter(s=>s.slug!==current).slice(0,3).map(service=><Link key={service.slug} href={`/${service.slug}/`} className="related">{service.title}<span aria-hidden="true">↗</span></Link>)}</div><style jsx>{`.related-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:16px;margin-top:48px}.related{border-top:1px solid #ffffff80;padding-top:18px;font-weight:700;display:flex;justify-content:space-between}.related span{font-size:1.3rem}@media(max-width:650px){.related-grid{grid-template-columns:1fr}}`}</style></section>; }
