'use client';

import Link from 'next/link';
import { allServices, ServicePage } from '../data';
import { QuoteForm } from './QuoteForm';

export function SectionHeading({ eyebrow, title, children, light = false }: { eyebrow?: string; title: string; children?: React.ReactNode; light?: boolean }) { return <div style={{maxWidth:850}}><p className="mono label" style={{color:light?'var(--red-bright)':'var(--red)'}}>{eyebrow}</p><h2 className="display" style={{fontSize:'clamp(3.5rem,8vw,8.25rem)',margin:0}}>{title}</h2>{children && <div style={{fontSize:'1.1rem',maxWidth:650,marginTop:24,color:light?'var(--muted)':'var(--muted-dark)'}}>{children}</div>}</div>; }

export function ImageTile({ image, title, href, copy, wide = false }: { image: string; title: string; href: string; copy: string; wide?: boolean }) { return <Link className={`media-tile ${wide?'wide':''}`} href={href}><img src={`/assets/${image}`} alt="" loading="lazy" /><span className="media-tile-content"><span className="mono">{title === 'Scope, in the field.' ? '' : title}</span><h3 className="display">{title}</h3><p>{copy} <span aria-hidden="true">↗</span></p></span></Link>; }

export function ServiceCard({ service }: { service: ServicePage }) { return <article className="service-card"><p className="mono">{service.category}</p><h3 className="display">{service.title}</h3><p>{service.intro}</p><Link href={`/${service.slug}/`} className="arrow-link">Explore service <span aria-hidden="true">↗</span></Link></article>; }

export function QuoteSection() { return <section id="quote" className="dark section"><div className="wrap quote-layout"><div><SectionHeading light eyebrow="Start with the scope" title="Let's get it gone."><p>Share project basics and preview a qualified request. The form is intentionally non-submitting until a provider is approved.</p></SectionHeading><a className="btn btn-outline" href="tel:8175978490">Call 817-597-8490</a></div><QuoteForm /></div></section>; }

export function ServiceDetail({ service }: { service: ServicePage }) { return <><section className="dark section detail-hero"><div className="wrap"><p className="mono" style={{color:'var(--red-bright)'}}>Services / {service.category}</p><h1 className="display">{service.title}</h1><p className="lead">{service.intro}</p><div className="hero-actions"><Link className="btn btn-primary" href="/contact-us/#quote">Get a free quote</Link><a className="btn btn-outline" href="tel:8175978490">817-597-8490</a></div></div></section><section className="section"><div className="wrap"><SectionHeading eyebrow="Scope" title="What's included" /><div className="item-grid">{service.items.map((item,index)=><div key={item} className="item"><span className="mono">0{index+1}</span><h3>{item}</h3></div>)}</div>{service.process && <div style={{marginTop:'clamp(4rem,8vw,8rem)'}}><SectionHeading eyebrow="Process" title="A clear path forward" /><div className="process-grid">{service.process.map((step,index)=><div key={step} className="process"><span className="display">0{index+1}</span><h3>{step}</h3></div>)}</div></div>}{service.note && <div className="note"><p className="mono">Why Matrix</p><p>{service.note}</p></div>}</div></section><RelatedServices current={service.slug} /><QuoteSection /></>; }

export function RelatedServices({ current }: { current: string }) { return <section className="red" style={{paddingBlock:'clamp(3rem,7vw,6rem)'}}><div className="wrap" style={{display:'flex',justifyContent:'space-between',alignItems:'end',gap:24,flexWrap:'wrap'}}><div><p className="mono">Keep exploring</p><h2 className="display" style={{fontSize:'clamp(3rem,6vw,6rem)',margin:0}}>More ways to move forward.</h2></div><Link className="btn btn-dark" href="/our-services/">View all services</Link></div><div className="wrap related-grid">{allServices.filter(s=>s.slug!==current).slice(0,3).map(service=><Link key={service.slug} href={`/${service.slug}/`} className="related">{service.title}<span aria-hidden="true">↗</span></Link>)}</div></section>; }
