'use client';

import { FormEvent, useState } from 'react';

export function QuoteForm({ compact = false }: { compact?: boolean }) {
  const [sent, setSent] = useState(false);
  function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setSent(true); }
  if (sent) return <div role="status" className="form-success"><p className="mono">Request ready</p><h3 className="display">Thank you.</h3><p>Your request is prepared for a Matrix Demolition representative. For immediate assistance, call <a href="tel:8175978490">817-597-8490</a>.</p></div>;
  return <form id="quote" onSubmit={submit} className="quote-form" aria-describedby="quote-help"><p id="quote-help" style={{marginTop:0,color:'var(--muted-dark)'}}>Fill out this short form. For immediate assistance, call <a href="tel:8175978490" style={{fontWeight:700}}>817-597-8490</a>.</p><div className={compact?'fields compact':'fields'}>
    <label>Name *<input name="name" required autoComplete="name" /></label><label>Phone *<input name="phone" type="tel" required autoComplete="tel" /></label><label>Email *<input name="email" type="email" required autoComplete="email" /></label>
    <label>Service needed *<select name="service" required defaultValue=""><option value="" disabled>Select a service</option><option>Demolition</option><option>Excavation</option><option>Site development</option><option>Disaster recovery</option><option>Ponds and lakes</option><option>Soil Remediation</option><option>Road construction</option><option>Pool demolition</option><option>Other</option></select></label>
    <label className="wide">Project city or address *<input name="location" required autoComplete="street-address" /></label><fieldset><legend>Project type</legend><label><input type="radio" name="projectType" value="Residential" /> Residential</label><label><input type="radio" name="projectType" value="Commercial" /> Commercial</label></fieldset>
    <label>Timeline<select name="timeline" defaultValue=""><option value="">Choose timeline</option><option>Emergency</option><option>This month</option><option>1–3 months</option><option>Planning</option></select></label><label>How did you hear about us?<select name="referral" defaultValue=""><option value="">Select one</option><option>Online</option><option>Word of mouth</option><option>Other</option></select></label><label className="wide">Short description<textarea name="description" rows={4} /></label>
    <label className="consent wide"><input type="checkbox" required /> I agree to be contacted about this request.</label><div aria-hidden="true" className="honeypot"><label>Website<input tabIndex={-1} name="website" autoComplete="off" /></label></div>
  </div><button className="btn btn-primary" type="submit">Get a free quote</button><style jsx>{`.quote-form{background:var(--white);color:var(--ink);padding:clamp(1.25rem,3vw,2.5rem);border:1px solid var(--bone-rule)}.fields{display:grid;grid-template-columns:1fr 1fr;gap:18px;margin:24px 0}.fields label,.fields fieldset{display:grid;gap:7px;font-weight:700;font-size:.9rem}.fields input:not([type=radio]):not([type=checkbox]),.fields select,.fields textarea{width:100%;min-height:44px;padding:10px;border:1px solid #9e9890;border-radius:4px;background:#fff;color:var(--ink)}.fields textarea{resize:vertical}.wide{grid-column:1/-1}.fields fieldset{grid-template-columns:auto auto;align-content:start;border:0;padding:0;margin:0}.fields legend{grid-column:1/-1;margin-bottom:2px}.fields fieldset label{display:flex;align-items:center;font-weight:400}.fields input[type=radio],.fields input[type=checkbox]{accent-color:var(--red);width:18px;height:18px}.consent{display:flex!important;grid-template-columns:auto 1fr;align-items:center;font-weight:400!important}.honeypot{position:absolute;left:-9999px}.form-success{background:var(--white);padding:32px;border:1px solid var(--bone-rule)}.form-success h3{font-size:clamp(3rem,8vw,6rem);margin:0}.form-success a{color:var(--red);font-weight:700}@media(max-width:650px){.fields{grid-template-columns:1fr}.wide{grid-column:auto}.fields fieldset{grid-template-columns:1fr 1fr}}`}</style></form>;
}
