export type ServicePage = { slug: string; title: string; intro: string; items: string[]; category: string; process?: string[]; note?: string };

export const services: ServicePage[] = [
  { slug:'demolition-services', title:'Demolition Services', intro:'Experienced demolition contractor for residential and commercial spaces across Dallas/Fort Worth. Trained technicians safely and efficiently bring down structures so each site is ready for its next construction project.', category:'Demolition', items:['Residential demolition','Commercial demolition','Complete demolition','Selective and gut-out demolition','Interior demolition','Exterior demolition','Pre-construction services','Site preparation'], note:'More than 30 years of interior and exterior demolition experience. Family-owned since 1989.' },
  { slug:'selective-demolition', title:'Selective Demolition Services', intro:'Maintain structural integrity while removing dated or non-functional parts. Selective demolition can minimize waste, lower cost, and shorten project length for modifications and extensions.', category:'Demolition', items:['Interior demolition','Selective demolition','Gut-out demolition','Material removal','Site preparation'], note:'Specialized work keeps the structure in place while making room for what comes next.' },
  { slug:'pool-demolition', title:'Pool Demolition & Removal', intro:'Pool demolition and removal for Dallas/Fort Worth properties, from the existing pool through site preparation for what comes next.', category:'Demolition', items:['In-ground pool demolition','Deck and patio demolition','Pool equipment removal','Site preparation for landscaping'], process:['Initial consultation and assessment','Permitting and preparation','Demolition and removal','Site cleanup and restoration'] },
  { slug:'excavation-services', title:'Excavation Company in DFW, Texas', intro:'Foundations start with excavation. Matrix Demolition provides excavation for construction projects, with GPS grading technology supporting quality work.', category:'Excavation & Earthwork', items:['Commercial excavation','Residential development','Building pad preparation','Soil stabilization','Mass excavation','Land clearing'] },
  { slug:'construction-site-development', title:'Construction Site Development', intro:'Site preparation for residential developments, commercial and industrial sites, landfills, sports complexes, schools, TXDOT roadways, and shopping centers.', category:'Excavation & Earthwork', items:['Clearing and demolition','Earthwork','Grading and sloping','Surveying','Land clearing','Site preparation','Land development','Sewers and storm-water','Fine grading'] },
  { slug:'disaster-recovery', title:'Disaster Recovery / Storm Damage Demolition', intro:'Texas weather is unpredictable. Matrix Demolition provides professional demolition and cleanup for damaged structures and properties.', category:'Demolition', items:['House and mobile home demolition','Storm, fire, flood, and hurricane damage removal','Excavating and backfilling','Lot clearing and leveling','Tree and brush removal','Environmental abatement','Debris load out and haul-off','Dumpster and disposal service','Garage, pool, slab, and driveway removal'] },
  { slug:'ponds-lakes', title:'Ponds and Lakes', intro:'Private lakes, retention ponds, and property water features excavated to meet site requirements.', category:'Water & Land', items:['Pond construction','Lake construction','Irrigation ponds','Farm and ranch ponds','Retention basins','Excavate land for pond or lake'] },
  { slug:'soil-remediation', title:'Soil Remediation', intro:'Prompt, correct, and cost-effective remediation excavation services when toxic chemicals or other materials appear in a soils report.', category:'Excavation & Earthwork', items:['Remediation excavation','Material removal','Site preparation','Soil excavation'] },
  { slug:'road-construction', title:'Road Construction Services in Texas', intro:'Modern road construction methods create durable roadways for varying traffic loads and conditions, with quality and structural integrity in mind.', category:'Infrastructure', items:['Turnkey service','Asphalt, gravel, and concrete paving','Expert planning','Heavy civil and earthwork','Project management','Demolition and excavation','Soil stabilization','Grading and land clearing','Road and street construction','Parking lot construction','Turn lane construction'] },
  { slug:'golf-course-excavation', title:'Golf Course Construction & Development', intro:'Precision excavation and course development that considers environmental conservation, land use, and the shape of the finished course.', category:'Water & Land', items:['Course and neighborhood development','Turnkey service','Grading and excavation','Terrain shaping','Aesthetic design implementation','Soil stabilization','Drainage and irrigation','Road construction','Land clearing'] },
];

export const utilityPages: ServicePage[] = [
  { slug:'silica-sand-mining', title:'Silica Sand Mining', intro:'Site and earthwork services for silica sand mining projects, shaped by the scope and requirements of each property.', category:'Excavation & Earthwork', items:['Site preparation','Excavation','Land clearing'] },
  { slug:'structural-demolition-services', title:'Structural Demolition Services', intro:'Structural demolition support for spaces preparing for their next construction phase.', category:'Demolition', items:['Complete demolition','Commercial demolition','Site preparation'] },
  { slug:'demolition-contractor-fort-worth-tx', title:'Demolition Contractor in Fort Worth, TX', intro:'Residential and commercial demolition services for projects in and around Fort Worth.', category:'Demolition', items:['Residential demolition','Commercial demolition','Selective demolition'] },
  { slug:'demolition-contractor-weatherford-tx', title:'Demolition Contractor in Weatherford, TX', intro:'Experienced demolition services for residential and commercial spaces in and around Weatherford.', category:'Demolition', items:['Complete demolition','Interior demolition','Site preparation'] },
  { slug:'excavation-company-fort-worth-tx', title:'Excavation Company in Fort Worth, TX', intro:'Excavation and earthwork services for construction projects in and around Fort Worth.', category:'Excavation & Earthwork', items:['Building pad preparation','Mass excavation','Land clearing'] },
  { slug:'excavation-contractors-weatherford-tx', title:'Excavation Contractors in Weatherford, TX', intro:'Excavation services for property and construction work in and around Weatherford.', category:'Excavation & Earthwork', items:['Commercial excavation','Soil stabilization','Site preparation'] },
];

export const allServices = [...services, ...utilityPages];
export const serviceBySlug = Object.fromEntries(allServices.map((service) => [service.slug, service])) as Record<string, ServicePage>;

export const navLinks = [
  ['Services','/our-services/'], ['Our Work','/our-work/'], ['Contact','/contact-us/'], ['Careers','/matrix-careers/'],
] as const;
