'use client';

import Link from 'next/link';
import { QuoteSection, SectionHeading, ServiceCard } from './components/Content';
import { services } from './data';

export default function Home() { return <>
  <section className="dark hero"><div className="wrap hero-inner"><div><p className="mono" style={{color:'var(--red-bright)'}}>Matrix Demolition LLC / Since 1989</p><h1 className="display">You pick the location.<br /><span style={{color:'var(--red-bright)'}}>We handle the rest.</span></h1><p className="hero-copy">Demolition and excavation services from a family-owned crew with more than 30 years of experience.</p><div className="hero-actions"><Link className="btn btn-primary" href="/contact-us/#quote">Get a free quote</Link><a className="btn btn-outline" href="tel:8175978490">Call 817-597-8490</a></div></div><div className="hero-mark" aria-hidden="true"><span>MD</span><small>DEMOLITION<br />EXCAVATION<br />SITE DEVELOPMENT</small></div></div><style jsx>{`.hero{min-height:clamp(600px,78vh,820px);display:grid;align-items:center;border-bottom:1px solid var(--rule)}.hero-inner{display:grid;grid-template-columns:1.4fr .6fr;gap:48px;align-items:end}.hero h1{font-size:clamp(4rem,10vw,10.25rem);margin:20px 0;max-width:1000px}.hero-copy{font-size:clamp(1rem,2vw,1.35rem);color:var(--muted);max-width:560px}.hero-actions{display:flex;flex-wrap:wrap;gap:12px;margin-top:32px}.hero-mark{border:1px solid var(--rule);aspect-ratio:1;display:grid;place-content:center;padding:32px;transform:rotate(3deg);background:var(--raised)}.hero-mark span{font:900 clamp(5rem,12vw,11rem)/.8 Impact, sans-serif;color:var(--red)}.hero-mark small{font-family:'Courier New',monospace;font-size:.65rem;letter-spacing:.15em;margin-top:24px;color:var(--muted)}@media(max-width:700px){.hero-inner{grid-template-columns:1fr}.hero-mark{display:none}.hero h1{font-size:clamp(3.6rem,15vw,6rem)}}`}</style></section>
  <section className="section"><div className="wrap"><div className="proof"><div><strong>Since 1989</strong><span>Family-owned</span></div><div><strong>30+ years</strong><span>Industry experience</span></div><div><strong>A+ BBB</strong><span>Source-supported claim</span></div></div><div className="home-intro"><SectionHeading eyebrow="Built for the next phase" title="Work that clears the way."><p>From demolition and excavation to site development and road construction, Matrix Demolition helps prepare spaces for what comes next.</p></SectionHeading><Link className="btn btn-dark" href="/our-services/">Explore services</Link></div><style>{`.proof{display:grid;grid-template-columns:repeat(3,1fr);border-block:1px solid var(--bone-rule);margin-bottom:clamp(5rem,11vw,10rem)}.proof div{padding:24px;border-right:1px solid var(--bone-rule)}.proof div:last-child{border:0}.proof strong,.proof span{display:block}.proof strong{font:700 clamp(1.7rem,3vw,3rem)/1 'Arial Narrow',Impact,sans-serif;text-transform:uppercase}.proof span{color:var(--muted-dark);margin-top:8px}.home-intro{display:flex;align-items:end;justify-content:space-between;gap:32px}.home-intro .btn{flex:none}@media(max-width:650px){.proof{grid-template-columns:1fr}.proof div{border-right:0;border-bottom:1px solid var(--bone-rule)}.home-intro{display:block}.home-intro .btn{margin-top:24px}}`}</style></div></section>
  <section className="dark section"><div className="wrap"><SectionHeading light eyebrow="What we do" title="Services with substance." /><div className="services-grid">{services.map(service=><ServiceCard key={service.slug} service={service} />)}</div></div><style jsx>{`.services-grid{display:grid;grid-template-columns:repeat(2,1fr);gap:0 56px;margin-top:64px}.services-grid :global(.service-card){border-color:var(--rule)}.services-grid :global(.service-card p:not(.mono)){color:var(--muted)}.services-grid :global(.service-card .arrow-link){color:var(--red-bright)}@media(max-width:700px){.services-grid{grid-template-columns:1fr;margin-top:40px}}`}</style></section>
  <section className="red section"><div className="wrap storm"><div><p className="mono">A direct path through difficult work</p><h2 className="display">Need to clear a site?</h2><p>Tell us about the property, scope, and timeline. We will start with the details you can confirm today.</p></div><Link className="btn btn-dark" href="/contact-us/#quote">Get a free quote</Link></div><style>{`.storm{display:flex;justify-content:space-between;align-items:end;gap:32px}.storm h2{font-size:clamp(3.4rem,8vw,8rem);margin:0}.storm p:not(.mono){max-width:520px;font-size:1.1rem}@media(max-width:600px){.storm{display:block}.storm .btn{margin-top:24px}}`}</style></section>
  <section className="section"><div className="wrap"><SectionHeading eyebrow="How work moves" title="A clear sequence." /><div className="process-grid home-process">{['Consultation','Permits and preparation','Work','Cleanup and restoration'].map((step,index)=><div key={step}><span className="display">0{index+1}</span><h3>{step}</h3></div>)}</div></div><style jsx>{`.home-process{display:grid;grid-template-columns:repeat(4,1fr);margin-top:56px}.home-process div{border-top:1px solid var(--bone-rule);padding:20px 16px 0;border-left:1px solid var(--bone-rule)}.home-process .display{color:var(--red);font-size:4rem}.home-process h3{font-size:1.15rem;margin-top:18px}@media(max-width:650px){.home-process{grid-template-columns:1fr 1fr}.home-process div{min-height:140px}}`}</style></section>
  <QuoteSection />
</>; }
